# Do not edit. Generated by the configure script.
PYTHON=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
BUILDTYPE=Release
USE_XCODE=0
NODE_TARGET_TYPE=static_library
PREFIX=/usr/local
